//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb_Nhom3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
        }

        [DisplayName("Mã người dùng")]
        public int MANGUOIDUNG { get; set; }
        [DisplayName("Họ và tên")]
        [Required(ErrorMessage= "Chưa nhập họ tên")]

        public string HOTEN { get; set; }
        [EmailAddress]
        [DisplayName("Email")]
        [Required(ErrorMessage = "Chưa nhập email")]
        public string EMAIL { get; set; }
        [DisplayName("Số điện thoại")]

        [Required(ErrorMessage = "Chưa nhập điện thoại")]
        public string DIENTHOAI { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Chưa nhập mật khẩu")]
        public string MATKHAU { get; set; }

        [DisplayName("ID Phân Quyền")]
        public Nullable<int> IDQUYEN { get; set; }
        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]
        public string DIACHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
        public virtual PHANQUYEN PHANQUYEN { get; set; }
    }
}
