//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb_Nhom3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
        }

        [DisplayName("Mã  Sản Phẩm")]
        [Required(ErrorMessage = "Chưa nhập Mã Sản phẩm")]
        public int MASP { get; set; }
        [DisplayName("Tên  Sản Phẩm")]
        [Required(ErrorMessage = "Chưa nhập Tên Sản phẩm")]
        public string TENSP { get; set; }
        [DisplayName("Giá tiền")]
        [Required(ErrorMessage = "Chưa nhập giá tiền")]
        public Nullable<decimal> GIATIEN { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Chưa nhập số lượng")]
        public Nullable<int> SOLUONG { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Chưa nhập mô tả")]
        public string MOTA { get; set; }
        [DisplayName("Ảnh bìa")]
        public string ANHBIA { get; set; }
        public Nullable<int> MALOAISP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
